### ISSUE TITLE
Initial customer counts show a strong initial oscillation 

### ISSUE THREAD

**Issue by mvanwyk** [Data-Simply/pyretailscience#11]
Below is a graph of the unique customer count transacting per day. You can see strong oscillations in the initial period. I believe this is due to the fact that all the starting customers are initialed on day 1 of the simulation, and their next purchase date is set with a Poisson distribution from this date, which obviously isn't realistic. I believe this is the reason for the initial oscillations around that distribution's mean seen in the graph.

![osscillations](https://github.com/Data-Simply/pyretailscience/assets/2493311/8e779138-dce2-454d-8bdb-9da4bab7dd4b)

I tried switching the _initial_ next purchase date with a uniform distribution between 0 and `average_days_between_purchases` and saw the graph below. There is a big dip in the number of customers purchasing after `average_days_between_purchases` days have passed.

![image](https://github.com/Data-Simply/pyretailscience/assets/2493311/6ea58752-36a3-4091-896c-ffc07392b8c8)

I also tried offsetting the initial transaction date selected from a poison distribution by adding or removing a uniform random value between 0 and `average_days_between_purchases`, but the results still look a little strange. 

@garve Any thoughts?

This is the config I was using for customers in the simulation.

```yaml
customers:
  # Number of customers to generate at the start of the simulation
  starting_number_of_customers: 2500
  # Probability that a customer will churn after their last purchase
  churn_probability: 0.10
  # Average days between purchases for a customer
  average_days_between_purchases: 30
  # Average number of new customers per day
  average_new_customers_per_day: 5
  ```
